FROM node:22

WORKDIR /app

# Copy package requirements
COPY package*.json ./

# Install dependecies
RUN npm install

# Copy everything from current directory
COPY . .

# Expose porth 3000 for use
EXPOSE 3000

# Start the server
CMD ["npm", "start"]